### PR TITLE
Fixed: Bump go codec to handle special char encoding and added unit test

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
Through a lengthy debug session, we had encountered an infinite loop issue within the go codec that we use in elemental. The following issue tracks both the fix and the related tickets: https://github.com/ugorji/go/pull/320

Added is the bump to latest codec and a unit test to cover the offending character.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-special-char-encoding",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "1ab4f15ffe6b7e01899ce94c2bcdaf96af07f349",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "enforcerd",
    "pr-id": "2495",
    "commit-sha": "350573d72dc6f63e85499a13a56b88bf317752e1",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "apotests",
    "pr-id": "3429",
    "commit-sha": "a8b1d24525eed45f9da64a321ef402c8a290ae78",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "b9510f10992c4f4a8f316c182859323b26b71463",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "b5dd29937cc9ea48e1c4f931a547eef15cc9893a",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "b9510f10992c4f4a8f316c182859323b26b71463",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "298f1462aa594f19c3d5908810e076e4a7652b49",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "b5dd29937cc9ea48e1c4f931a547eef15cc9893a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "298f1462aa594f19c3d5908810e076e4a7652b49",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "5f2addb48fb07b2849dd7a36932574e00df0d870",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "5f2addb48fb07b2849dd7a36932574e00df0d870",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "d91ed012c77329c67342b4cb98f0db35d868a522",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "5f2addb48fb07b2849dd7a36932574e00df0d870",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "1fc93ba1e4d155714894384ea5b1b01bc93793c9",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "5f2addb48fb07b2849dd7a36932574e00df0d870",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "de26f36763f3cd0ec9cd55371d4ece51b7681106",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-special-char-encoding",
    "component": "backend",
    "pr-id": "1260",
    "commit-sha": "5f2addb48fb07b2849dd7a36932574e00df0d870",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "enforcerd",
    "pr-id": "2495",
    "commit-sha": "350573d72dc6f63e85499a13a56b88bf317752e1",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "apotests",
    "pr-id": "3429",
    "commit-sha": "a8b1d24525eed45f9da64a321ef402c8a290ae78",
    "pipeline": "master"
  },
  {
    "project": "fix-special-char-encoding",
    "component": "elemental",
    "pr-id": "101",
    "commit-sha": "c69446755f5db4d6e82472598879341b9a7d4160",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
